// <auto-generated />
using AdminSerives.Dao;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminSerives.Migrations
{
    [DbContext(typeof(APpDB))]
    partial class APpDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AdminSerives.Models.Admin", b =>
                {
                    b.Property<int>("Autoid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Autoid"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Autoid");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            Autoid = 1,
                            Name = "Srinu",
                            Salary = "10000"
                        },
                        new
                        {
                            Autoid = 2,
                            Name = "Gopi",
                            Salary = "20000"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
